# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketSerial.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketSerial.proto',
  package='PacketSerialData',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12PacketSerial.proto\x12\x10PacketSerialData\"G\n\x11\x44\x61taElementSerial\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61taType\x18\x02 \x01(\x05\x12\x12\n\nstructType\x18\x03 \x01(\x05\"^\n\x0cPacketSerial\x12\x12\n\npacketType\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x0e\n\x06\x63mdNum\x18\x04 \x01(\x05\x12\x0c\n\x04sock\x18\x05 \x01(\x05\"X\n\x13SendCmdPacketSerial\x12.\n\x06packet\x18\x01 \x01(\x0b\x32\x1e.PacketSerialData.PacketSerial\x12\x11\n\tcmdVector\x18\x02 \x03(\t\"Z\n\x10RecvPacketSerial\x12.\n\x06packet\x18\x01 \x01(\x0b\x32\x1e.PacketSerialData.PacketSerial\x12\x16\n\x0erecvPacketType\x18\x02 \x01(\x05\"\x81\x01\n\x14RecvDataPacketSerial\x12\x36\n\nrecvPacket\x18\x01 \x01(\x0b\x32\".PacketSerialData.RecvPacketSerial\x12\x31\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32#.PacketSerialData.DataElementSerial\"Z\n\x13RecvMsgPacketSerial\x12\x36\n\nrecvPacket\x18\x01 \x01(\x0b\x32\".PacketSerialData.RecvPacketSerial\x12\x0b\n\x03msg\x18\x02 \x01(\t\"T\n\x12SignalPacketSerial\x12.\n\x06packet\x18\x01 \x01(\x0b\x32\x1e.PacketSerialData.PacketSerial\x12\x0e\n\x06signal\x18\x02 \x01(\x05\"b\n\x0fLogPacketSerial\x12.\n\x06packet\x18\x01 \x01(\x0b\x32\x1e.PacketSerialData.PacketSerial\x12\x12\n\ndateformat\x18\x02 \x01(\t\x12\x0b\n\x03str\x18\x03 \x01(\tb\x06proto3')
)




_DATAELEMENTSERIAL = _descriptor.Descriptor(
  name='DataElementSerial',
  full_name='PacketSerialData.DataElementSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PacketSerialData.DataElementSerial.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='PacketSerialData.DataElementSerial.dataType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='structType', full_name='PacketSerialData.DataElementSerial.structType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=111,
)


_PACKETSERIAL = _descriptor.Descriptor(
  name='PacketSerial',
  full_name='PacketSerialData.PacketSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetType', full_name='PacketSerialData.PacketSerial.packetType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='PacketSerialData.PacketSerial.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IP', full_name='PacketSerialData.PacketSerial.IP', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmdNum', full_name='PacketSerialData.PacketSerial.cmdNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sock', full_name='PacketSerialData.PacketSerial.sock', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=207,
)


_SENDCMDPACKETSERIAL = _descriptor.Descriptor(
  name='SendCmdPacketSerial',
  full_name='PacketSerialData.SendCmdPacketSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='PacketSerialData.SendCmdPacketSerial.packet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmdVector', full_name='PacketSerialData.SendCmdPacketSerial.cmdVector', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=297,
)


_RECVPACKETSERIAL = _descriptor.Descriptor(
  name='RecvPacketSerial',
  full_name='PacketSerialData.RecvPacketSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='PacketSerialData.RecvPacketSerial.packet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recvPacketType', full_name='PacketSerialData.RecvPacketSerial.recvPacketType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=389,
)


_RECVDATAPACKETSERIAL = _descriptor.Descriptor(
  name='RecvDataPacketSerial',
  full_name='PacketSerialData.RecvDataPacketSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recvPacket', full_name='PacketSerialData.RecvDataPacketSerial.recvPacket', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='PacketSerialData.RecvDataPacketSerial.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=521,
)


_RECVMSGPACKETSERIAL = _descriptor.Descriptor(
  name='RecvMsgPacketSerial',
  full_name='PacketSerialData.RecvMsgPacketSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recvPacket', full_name='PacketSerialData.RecvMsgPacketSerial.recvPacket', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='PacketSerialData.RecvMsgPacketSerial.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=613,
)


_SIGNALPACKETSERIAL = _descriptor.Descriptor(
  name='SignalPacketSerial',
  full_name='PacketSerialData.SignalPacketSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='PacketSerialData.SignalPacketSerial.packet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal', full_name='PacketSerialData.SignalPacketSerial.signal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=699,
)


_LOGPACKETSERIAL = _descriptor.Descriptor(
  name='LogPacketSerial',
  full_name='PacketSerialData.LogPacketSerial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='PacketSerialData.LogPacketSerial.packet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dateformat', full_name='PacketSerialData.LogPacketSerial.dateformat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str', full_name='PacketSerialData.LogPacketSerial.str', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=701,
  serialized_end=799,
)

_SENDCMDPACKETSERIAL.fields_by_name['packet'].message_type = _PACKETSERIAL
_RECVPACKETSERIAL.fields_by_name['packet'].message_type = _PACKETSERIAL
_RECVDATAPACKETSERIAL.fields_by_name['recvPacket'].message_type = _RECVPACKETSERIAL
_RECVDATAPACKETSERIAL.fields_by_name['data'].message_type = _DATAELEMENTSERIAL
_RECVMSGPACKETSERIAL.fields_by_name['recvPacket'].message_type = _RECVPACKETSERIAL
_SIGNALPACKETSERIAL.fields_by_name['packet'].message_type = _PACKETSERIAL
_LOGPACKETSERIAL.fields_by_name['packet'].message_type = _PACKETSERIAL
DESCRIPTOR.message_types_by_name['DataElementSerial'] = _DATAELEMENTSERIAL
DESCRIPTOR.message_types_by_name['PacketSerial'] = _PACKETSERIAL
DESCRIPTOR.message_types_by_name['SendCmdPacketSerial'] = _SENDCMDPACKETSERIAL
DESCRIPTOR.message_types_by_name['RecvPacketSerial'] = _RECVPACKETSERIAL
DESCRIPTOR.message_types_by_name['RecvDataPacketSerial'] = _RECVDATAPACKETSERIAL
DESCRIPTOR.message_types_by_name['RecvMsgPacketSerial'] = _RECVMSGPACKETSERIAL
DESCRIPTOR.message_types_by_name['SignalPacketSerial'] = _SIGNALPACKETSERIAL
DESCRIPTOR.message_types_by_name['LogPacketSerial'] = _LOGPACKETSERIAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataElementSerial = _reflection.GeneratedProtocolMessageType('DataElementSerial', (_message.Message,), {
  'DESCRIPTOR' : _DATAELEMENTSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.DataElementSerial)
  })
_sym_db.RegisterMessage(DataElementSerial)

PacketSerial = _reflection.GeneratedProtocolMessageType('PacketSerial', (_message.Message,), {
  'DESCRIPTOR' : _PACKETSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.PacketSerial)
  })
_sym_db.RegisterMessage(PacketSerial)

SendCmdPacketSerial = _reflection.GeneratedProtocolMessageType('SendCmdPacketSerial', (_message.Message,), {
  'DESCRIPTOR' : _SENDCMDPACKETSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.SendCmdPacketSerial)
  })
_sym_db.RegisterMessage(SendCmdPacketSerial)

RecvPacketSerial = _reflection.GeneratedProtocolMessageType('RecvPacketSerial', (_message.Message,), {
  'DESCRIPTOR' : _RECVPACKETSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.RecvPacketSerial)
  })
_sym_db.RegisterMessage(RecvPacketSerial)

RecvDataPacketSerial = _reflection.GeneratedProtocolMessageType('RecvDataPacketSerial', (_message.Message,), {
  'DESCRIPTOR' : _RECVDATAPACKETSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.RecvDataPacketSerial)
  })
_sym_db.RegisterMessage(RecvDataPacketSerial)

RecvMsgPacketSerial = _reflection.GeneratedProtocolMessageType('RecvMsgPacketSerial', (_message.Message,), {
  'DESCRIPTOR' : _RECVMSGPACKETSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.RecvMsgPacketSerial)
  })
_sym_db.RegisterMessage(RecvMsgPacketSerial)

SignalPacketSerial = _reflection.GeneratedProtocolMessageType('SignalPacketSerial', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALPACKETSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.SignalPacketSerial)
  })
_sym_db.RegisterMessage(SignalPacketSerial)

LogPacketSerial = _reflection.GeneratedProtocolMessageType('LogPacketSerial', (_message.Message,), {
  'DESCRIPTOR' : _LOGPACKETSERIAL,
  '__module__' : 'PacketSerial_pb2'
  # @@protoc_insertion_point(class_scope:PacketSerialData.LogPacketSerial)
  })
_sym_db.RegisterMessage(LogPacketSerial)


# @@protoc_insertion_point(module_scope)
